### ISSUE TITLE
Cho xin thông tin database và cms angular đang bị lỗi

### ISSUE THREAD

**Issue by mithang** [anglesen1120/HDNXUdemy_BE#9]

**Comment by anglesen1120** [comment]
bạn ơi, thông tin database thì bạn phải tự tạo dưới local bạn, mình làm code first thì bạn phải tự host db dưới local, còn angular cms đang bị lỗi, thì bạn đọc lỗi rồi re-search cách fix á bạn! đó cũng là 1 cách học á

**Comment by anglesen1120** [comment]
với thêm 1 cái nữa, để nhờ giúp đỡ, hãy học lại cách viết văn hoặc nói làm sao để người ta có thể sẵn sáng giúp bạn, nói theo cách của bạn thì mình có muốn giúp mình cũng không giúp đâu bạn! sorry bạn

**Comment by anglesen1120** [comment]
Close
